set_program:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: kospel
    schedule_type:
      required: true
      selector:
        select:
          options:
            - ch
            - dhw
            - circulation
    program_id:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box
    slots:
      required: true
      selector:
        object: {}

set_weekday_schedule:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: kospel
    schedule_type:
      required: true
      selector:
        select:
          options:
            - ch
            - dhw
            - circulation
    monday:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box
    tuesday:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box
    wednesday:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box
    thursday:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box
    friday:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box
    saturday:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box
    sunday:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box

get_program:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: kospel
    schedule_type:
      required: true
      selector:
        select:
          options:
            - ch
            - dhw
            - circulation
    program_id:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box

get_weekday_schedule:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: kospel
    schedule_type:
      required: true
      selector:
        select:
          options:
            - ch
            - dhw
            - circulation
